### ISSUE TITLE
Neo4j locking with simple session API prevents the simulation from completing

### ISSUE THREAD

**Issue by jmsfltchr** [typedb/typedb-benchmark#70]
## Description

Working with Neo4j with concurrent transactions (and therefore concurrent sessions since each session can only have one transaction open at a time), I have encountered issues with resource locking. I have been using the [Simple Session API](https://neo4j.com/docs/driver-manual/current/session-api/simple/) since this allows us to pass transactions around the application as wish, in an abstracted way that is agnostic to the DB backend the simulation is being used on. This means, however, that we are not leveraging the automatic transaction management that comes with the [transaction function mechanism](https://neo4j.com/docs/driver-manual/current/cypher-workflow/#driver-transactions).

In this case we non-deteministically suffer this error:

```
org.neo4j.driver.exceptions.TransientException: LockClient[62] can't wait on resource RWLock[RELATIONSHIP(38), hash=504460055] since => LockClient[62] <-[:HELD_BY]- RWLock[RELATIONSHIP(58), hash=1189853422] <-[:WAITING_FOR]- LockClient[65] <-[:HELD_BY]- RWLock[RELATIONSHIP(38), hash=504460055]
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
	at org.neo4j.driver.internal.InternalTransaction.commit(InternalTransaction.java:39)
	at grakn.simulation.db.neo4j.driver.Neo4jDriverWrapper$Session$Transaction.commit(Neo4jDriverWrapper.java:69)
	at grakn.simulation.db.common.agents.interaction.RelocationAgent.iterate(RelocationAgent.java:38)
	at grakn.simulation.db.common.agents.base.AgentRunner.runAgent(AgentRunner.java:67)
	at grakn.simulation.db.common.agents.base.AgentRunner.lambda$iterate$0(AgentRunner.java:54)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
		at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:83)
		at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:105)
		at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.unpackFailureMessage(MessageReaderV1.java:83)
		at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:59)
		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
		at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
		at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)
```

Relevant posts:
https://stackoverflow.com/questions/39168231/neo4j-cant-wait-on-resource-lock-error
https://github.com/neo4j/neo4j/issues/12040

We can see that this will arise due to Neo4j's [default locking behaviour](https://neo4j.com/docs/java-reference/current/transaction-management/locking/)

Having seen their [Deadlock handling example code](https://neo4j.com/docs/java-reference/current/transaction-management/deadlocks/#transactions-deadlocks-code), I tried modifying this to implement our own transient error handling so that we can keep transaction behaviour agnostic of Grakn/Neo4j/other backend being used.

Doing so, I encountered the following error. I can't find any info online for this `CIRCULAR REFERENCE`. It seems like state that is not easy to recover from, that occurred because agents were trying to write an edge to the same node. Presently I have worked around this issue by changing the nature of the queries so that they will no longer need to write an edge to the same node.

```
Jul 20, 2020 5:59:59 PM org.neo4j.driver.internal.logging.JULogger info
INFO: Closing driver instance 1100767002
Jul 20, 2020 5:59:59 PM org.neo4j.driver.internal.logging.JULogger info
INFO: Closing connection pool towards localhost:7687
org.neo4j.driver.exceptions.ClientException: Cannot run more queries in this transaction, it has either experienced an fatal error or was explicitly terminated
	at org.neo4j.driver.internal.async.UnmanagedTransaction.ensureCanRunQueries(UnmanagedTransaction.java:240)
	at org.neo4j.driver.internal.async.UnmanagedTransaction.runAsync(UnmanagedTransaction.java:197)
	at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:60)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:37)
	at grakn.simulation.db.neo4j.driver.Neo4jDriverWrapper.run(Neo4jDriverWrapper.java:128)
	at grakn.simulation.db.neo4j.agents.interaction.TransactionAgent.insertTransaction(TransactionAgent.java:55)
	at grakn.simulation.db.common.agents.interaction.TransactionAgent.lambda$iterate$0(TransactionAgent.java:39)
	at grakn.simulation.db.common.agents.utils.Allocation.allocate(Allocation.java:41)
	at grakn.simulation.db.common.agents.interaction.TransactionAgent.iterate(TransactionAgent.java:35)
	at grakn.simulation.db.common.agents.base.AgentRunner.runAgent(AgentRunner.java:67)
	at grakn.simulation.db.common.agents.base.AgentRunner.lambda$iterate$0(AgentRunner.java:54)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: org.neo4j.driver.exceptions.TransientException: LockClient[254] can't wait on resource RWLock[NODE(388), hash=972913835] since => LockClient[254] <-[:HELD_BY]- RWLock[NODE(831), hash=1926789033] <-[:WAITING_FOR]- LockClient[250] <-[:HELD_BY]- RWLock[NODE(388), hash=972913835]
		at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143)
		at org.neo4j.driver.internal.InternalTransaction.close(InternalTransaction.java:53)
		at grakn.simulation.db.neo4j.driver.Neo4jDriverWrapper$Session$Transaction.close(Neo4jDriverWrapper.java:75)
		at grakn.simulation.db.common.agents.base.Agent.closeTx(Agent.java:92)
		at grakn.simulation.db.common.agents.base.Agent.close(Agent.java:127)
		at grakn.simulation.db.common.agents.base.AgentRunner.runAgent(AgentRunner.java:64)
		... 10 more
		Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
			at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:83)
			at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:105)
			at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.unpackFailureMessage(MessageReaderV1.java:83)
			at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:59)
			at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
			at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
			at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
			at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
			at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
			at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
			at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
			at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
			at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
			at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
			at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
			at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
			at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
			at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
			at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
			at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
			at java.lang.Thread.run(Thread.java:748)
	[CIRCULAR REFERENCE:org.neo4j.driver.exceptions.TransientException: LockClient[254] can't wait on resource RWLock[NODE(388), hash=972913835] since => LockClient[254] <-[:HELD_BY]- RWLock[NODE(831), hash=1926789033] <-[:WAITING_FOR]- LockClient[250] <-[:HELD_BY]- RWLock[NODE(388), hash=972913835]]
```

**Comment by jmsfltchr** [comment]
Changing the scope of how sessions are opened in the simulation solved this issue. This was caused because Neo4j locks everything about a node in order to write an edge to it. The agents using different sessions therefore can't write to overlapping nodes, so the behaviour was changed such that agents working in parallel won't have nodes in common to write to.
